name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  paths:
    - 'reactiveland-basics/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#    - name: purge-cache
#      uses: MyAlbum/purge-cache@v1
#      with:
#        token: '${{ secrets.GITHUB_TOKEN }}'
#        debug: true

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Build reactiveland-basics
      working-directory: ./reactiveland-basics
      run: ./gradlew clean test
