name: Markdown to html

on:
  push:
    branches: ["main"]
    paths:
      - 'blog/posts/**'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "markdown"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1
        with:
          path: blog/posts/mutual-like-match-making/README.md
          outputpath: blog/public

      - name: checkout to a temp branch
        run: |
          git config --global user.email "bmd579@gmail.com"
          git config --global user.name "Mahdi"
          git checkout master
          git pull
          git checkout -b deployment-to-github-pages
          git add --all
          git commit -m "deployment-to-github-pages"
          git push origin HEAD:deployment-to-github-pages --force

      - name: create pull request
        run: gh pr merge --auto --rebase --delete-branch $(gh pr create -B master -H deployment-to-github-pages --title 'Merge deployment-to-github-pages into master for github pages' --body 'Created by Github action' --fill)
        env:
          GITHUB_TOKEN: ${{ secrets.BMD_ACCESS_TOKEN_FOR_ACTIONS }}
