name: Markdown to html

on:
  push:
    branches: ["main"]
    paths:
      - 'blog/posts/**'
      - '.github/workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "markdown"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: blog/posts/mutual-like-match-making/README.md
          output: blog/public/match-making.html
          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>

      - name: checkout to a temp branch
        run: |
          git config --global user.email "bmd579@gmail.com"
          git config --global user.name "Mahdi"
          git checkout master
          git pull
          git checkout -b deployment-to-github-pages
          git add --all
          git commit -m "deployment-to-github-pages"
          git push origin HEAD:deployment-to-github-pages --force

      - name: create pull request
        run: gh pr merge --auto --rebase --delete-branch $(gh pr create -B master -H deployment-to-github-pages --title 'Merge deployment-to-github-pages into master for github pages' --body 'Created by Github action' --fill)
        env:
          GITHUB_TOKEN: ${{ secrets.BMD_ACCESS_TOKEN_FOR_ACTIONS }}
